
dbsnp: /home/campbell/share/datasets/dbsnp/population_frequency/freq.vcf.gz

vartrix: /home/campbell/share/software/vartrix_linux

cellsnp: /home/campbell/share/software/cellsnp-lite/cellsnp-lite

fasta: /home/campbell/share/datasets/references/cellranger/refdata-gex-GRCh38-2020-A/fasta/genome.fa

cellranger_base_path: /home/campbell/share/datasets/peng-2019-cellranger

chrmap: chr-map.txt

snpdata: snp-data/genome1K.phase3.SNP_AF5e4.chr1toX.hg38.vcf.gz

ids:
  - CRR034499
  - CRR034500
  - CRR034501
  - CRR034503
  - CRR034504
  - CRR034505
  - CRR034506
  - CRR034507
  - CRR034509
  - CRR034510
  - CRR034511
  - CRR034512
  - CRR034513
  - CRR034516
  - CRR034517
  - CRR034518
  - CRR034519
  - CRR034520
  - CRR034521
  - CRR034522
  - CRR034523
  - CRR034524
  - CRR034525
  - CRR034526
  - CRR034527
  - CRR034528
  - CRR034529
  - CRR034530
  - CRR241798
  - CRR241799
  - CRR241800
  - CRR241801
  - CRR241802
  - CRR241803
  - CRR241804
  - CRR241805


